export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';

export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const CLIENT_LOGOUT = "CLIENT_LOGOUT"
